### PR TITLE
Add support for Session State Change

### LINKED ISSUE #87: [Feature Request] Add the SessionState Trigger Options
## Description
We want to roll out a schedule task that executes on workstation login. e.g. When a user unlocks their machine. Currently that isn't implemented in the gem.

This is supported in the OLE:
https://learn.microsoft.com/en-us/windows/win32/taskschd/sessionstatechangetrigger-statechange

The corresponding XML would look something similar to:
```
<SessionStateChangeTrigger>
    <Enabled>true</Enabled>
    <StateChange>SessionUnlock</StateChange>
</SessionStateChangeTrigger>
```

I'm happy to take a stab at this once I get up to speed on proper gem testing, etc.

## Windows Version
Windows 10/11/Server/etc.

## Replication Case
Not currently possible.

### PR DESCRIPTION
**Pull request by HeyItsGilbert**
### Description
This adds support for Session State Change. This would allow tasks that happen on Lock/Unlock, RDP connection/disconnect, and Console Login/Logoff.

### Issues Resolved

#87 

### Check List

- [x] New functionality includes tests
- [x] All tests pass
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by HeyItsGilbert** [comment]
Would be nice if we had a github action to run the spec tests and include them in PR's. Let me know if ya'll are interested in that and I can submit another PR.

**Review by jaymzh — COMMENTED** [review]
This code looks reasonable, though I admit I don't fully grok this codebase.

But merging without tests seems scary, so yes, if yo'ud be willing to make a PR to add GH test for the specs that'd be *great*. Thanks!

**Comment by HeyItsGilbert** [comment]
Looks like `chef/mixlib-shellout` relies on buildkite for that info. Not sure if folks want to plug into that or if a GH action would be preferred. Do we want to include that in this PR or should I do another?

**Comment by tpowell-progress** [comment]
> Looks like `chef/mixlib-shellout` relies on buildkite for that info. Not sure if folks want to plug into that or if a GH action would be preferred. Do we want to include that in this PR or should I do another?

My instinct prefers the GitHub Actions route, but I'm willing to be convinced otherwise if that route has roadblocks with this code base.

**Comment by jaymzh** [comment]
I also prefer Actions. You can see `chef/chef` for an example. However, some stuff may only be available in buildkite, feel free to copy-paste that stuff if necessary. Definitely a separate PR, please.

**Comment by HeyItsGilbert** [comment]
Screwed up my branches (commited this main). #90 is the new PR. My bad!

**Pull request closed without merging**
